name: CI

on:
  push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          strace tail -n1 LICENSE
          make docker
          docker run -it --rm strace tail -n1 LICENSE

